export const cars = [
  {
    car: "Mahindra Thar",
    cost: 2200000,
    img: "/images/thar1.jpg",
    maker: "Mahindra",
    type: "SUV",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Mahindra XUV 700",
    cost: 3115000,
    img: "/images/xuv_700.webp",
    maker: "Mahindra",
    type: "SUV",
    fuel_type: "Diesel",
    drivetrain: "AWD",
  },
  {
    car: "Hyundai I20",
    cost: 1000000,
    img: "/images/i20.webp",
    maker: "Hyundai",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Ford Mustang Shelby GT500",
    cost: 9000000,
    img: "/images/mustang_shelby.jpg",
    maker: "Ford",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Porsche 911 Carrera Cabriolet S",
    cost: 24800000,
    img: "/images/911_carrera_cabriolet.jpeg",
    maker: "Porsche",
    type: "Convertible",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Maserati GranTurismo",
    cost: 25871877,
    img: "/images/m_gt.webp",
    maker: "Maserati",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Lamborghini Revuelto",
    cost: 102136420,
    img: "/images/lambhorghini_r.webp",
    maker: "Lamborghini",
    type: "Sports",
    fuel_type: "Hybrid",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes-Benz AMG A 45 S",
    cost: 9400000,
    img: "/images/amg_45S.webp",
    maker: "Mercedes",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Tesla Cybertruck",
    cost: 20000000,
    img: "/images/cybertruck.png",
    maker: "Tesla",
    type: "Pickup",
    fuel_type: "Electric",
    drivetrain: "AWD",
  },
  {
    car: "Volvo XC60",
    cost: 8000000,
    img: "/images/xc60.webp",
    maker: "Volvo",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes Benz GLC",
    cost: 9400000,
    img: "/images/benz_glc.avif",
    maker: "Mercedes",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Jaguar F pace",
    cost: 9129785,
    img: "/images/fpace.webp",
    maker: "Jaguar",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Porsche Macan S",
    cost: 17945719,
    img: "/images/macan.jpeg",
    maker: "Porsche",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Porsche Cayenne",
    cost: 25161254,
    img: "/images/cayenne.webp",
    maker: "Porsche",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes S 680 Guard",
    cost: 100000000,
    img: "/images/Merc_S680_guard.jpg",
    maker: "Mercedes",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Rolls Royce Ghost",
    cost: 79854000,
    img: "/images/RR_GHOST.jpg",
    maker: "Rolls Royce",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Range Rover Sport",
    cost: 17500000,
    img: "/images/rr_sport.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Jeep Compas 4x4",
    cost: 4044000,
    img: "/images/Jeep_compass.jpg",
    maker: "Jeep",
    type: "Compact SUV",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Porsche Taycan Turbo S",
    cost: 26500000,
    img: "/images/taycan.jpg",
    maker: "Porsche",
    type: "Sports",
    fuel_type: "Electric",
    drivetrain: "AWD",
  },
  {
    car: "Toyota Glanza",
    cost: 1113000,
    img: "/images/glanza.webp",
    maker: "Toyota",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Tesla Model S Plaid",
    cost: 18000000,
    img: "/images/s_plaid.avif",
    maker: "Tesla",
    type: "Sedan",
    fuel_type: "Electric",
    drivetrain: "AWD",
  },
  {
    car: "Ferrari SF90 Stradale",
    cost: 86171403,
    img: "/images/sf90.webp",
    maker: "Ferrari",
    type: "Sports",
    fuel_type: "Hybrid",
    drivetrain: "AWD",
  },
  {
    car: "Toyota Hilux",
    cost: 4741659,
    img: "/images/hilux.webp",
    maker: "Toyota",
    type: "Pickup",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Maruti Eeco Cargo",
    cost: 816000,
    img: "/images/eeco_cargo.webp",
    maker: "Maruti",
    type: "Minivan",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Mercedes Benz A class",
    cost: 5753000,
    img: "/images/merc_a_class.webp",
    maker: "Mercedes",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Porsche 718 Boxster",
    cost: 19020960,
    img: "/images/718_boxster.jpg",
    maker: "Porsche",
    type: "Convertible",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Toyota Fortuner",
    cost: 5291374,
    img: "/images/fortuner.webp",
    maker: "Toyota",
    type: "SUV",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Range Rover Sentinel",
    cost: 120000000,
    img: "/images/rr_sentinel.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Rolls-Royce Cullinan",
    cost: 79854310,
    img: "/images/cullinan.webp",
    maker: "Rolls Royce",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Isuzu Dmax",
    cost: 3895000,
    img: "/images/dmax.jpg",
    maker: "Isuzu",
    type: "Pickup",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Scorpio N",
    cost: 3400000,
    img: "/images/scorpio_N.webp",
    maker: "Mahindra",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Mercedes S Class Maybach",
    cost: 42900000,
    img: "/images/maybach_s_blue.webp",
    maker: "Mercedes",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW 2 Series",
    cost: 5865144,
    img: "/images/bmw_2series.webp",
    maker: "BMW",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Modified Innvova",
    cost: 5000000,
    img: "/images/innova.jpeg",
    maker: "Modified",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Modified Hilux",
    cost: 10000000,
    img: "/images/mod_hilux.jpg",
    maker: "Modified",
    type: "Pickup",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Volvo S90",
    cost: 8800000,
    img: "/images/s90.webp",
    maker: "Volvo",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Volkswagen Virtus",
    cost: 2412000,
    img: "/images/virtus.webp",
    maker: "Volkswagen",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Skoda Slavia",
    cost: 2377000,
    img: "/images/slavia.webp",
    maker: "Skoda",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Mercedes S Class",
    cost: 23300000,
    img: "/images/s_class.webp",
    maker: "Mercedes",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Jeep Wrangler Rubicon",
    cost: 7800000,
    img: "/images/sage_green_rubicon.jpg",
    maker: "Jeep",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Bullet Proof Fortuner",
    cost: 12000000,
    img: "/images/BP_fortuner.webp",
    maker: "Modified",
    type: "SUV",
    fuel_type: "Diesel",
    drivetrain: "4x4",
  },
  {
    car: "Range Rover",
    cost: 32027075,
    img: "/images/rr_golden.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Porsche Panamera",
    cost: 19274534,
    img: "/images/panamera.webp",
    maker: "Porsche",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes GLS",
    cost: 16538816,
    img: "/images/gls.webp",
    maker: "Mercedes",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Range Rover Velar",
    cost: 11000000,
    img: "/images/velar_side.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Bentley Continental GTC S",
    cost: 74200000,
    img: "/images/bentley_gts.jpg",
    maker: "Bentley",
    type: "Convertible",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "BMW X1",
    cost: 6319000,
    img: "/images/bmw_x1.jpeg",
    maker: "BMW",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW X7",
    cost: 17000000,
    img: "/images/bmw_x7.avif",
    maker: "BMW",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW 3 Series Gran Limusine",
    cost: 7219000,
    img: "/images/BMW3GL.jpg",
    maker: "BMW",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW 5 Series",
    cost: 9129785,
    img: "/images/5_series.jpg",
    maker: "BMW",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Land Rover Defender",
    cost: 17344009,
    img: "/images/land_r_defender.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Land Rover Discovery Sport",
    cost: 8500000,
    img: "/images/discovery_sport.webp",
    maker: "Land Rover",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Toyota Land Cruiser",
    cost: 24674033,
    img: "/images/land_cruiser.webp",
    maker: "Toyota",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "4x4",
  },
  {
    car: "Mercedes-Benz AMG E 53 Cabriolet",
    cost: 15000000,
    img: "/images/MercE53.webp",
    maker: "Mercedes",
    type: "Convertible",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Lexus LX",
    cost: 33323188,
    img: "/images/lexus_lx.webp",
    maker: "Lexus",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Bentley Flying Spur",
    cost: 87500000,
    img: "/images/mulliner.webp",
    maker: "Bentley",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW 7 Series",
    cost: 22948032,
    img: "/images/7_series.webp",
    maker: "BMW",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Lamborghini Urus",
    cost: 48000000,
    img: "/images/urus_bhagwa.jpg",
    maker: "Lamborghini",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Lamborghini Huracan",
    cost: 47695874,
    img: "/images/saffron_lambo.jpg",
    maker: "Lamborghini",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Aston Martin DB12",
    cost: 52748237,
    img: "/images/aston.webp",
    maker: "Aston Martin",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Mercedes GLS 600 Maybach",
    cost: 36100000,
    img: "/images/merc_gls_600_maybach.webp",
    maker: "Mercedes",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes Benz AMG G Wagon Invictus",
    cost: 128000000,
    img: "/images/g_wagon_invicto.webp",
    maker: "Mercedes",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Mercedes Benz G Wagon",
    cost: 31862464,
    img: "/images/g63.jpg",
    maker: "Mercedes",
    type: "SUV",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Rolls Royce Phantom",
    cost: 112000000,
    img: "/images/rr_phantom.avif",
    maker: "Rolls Royce",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Meserati Quatraporte",
    cost: 23200000,
    img: "/images/Maserati_Quattroporte.webp",
    maker: "Maserati",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW M340i",
    cost: 8900000,
    img: "/images/m340i.jpg",
    maker: "BMW",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "BMW Z4",
    cost: 11534244,
    img: "/images/z4.webp",
    maker: "BMW",
    type: "Convertible",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Mercedes E class",
    cost: 9523019,
    img: "/images/e_class_lwb_2.webp",
    maker: "Mercedes",
    type: "Sedan",
    fuel_type: "Petrol",
    drivetrain: "AWD",
  },
  {
    car: "Ferrari Roma",
    cost: 43215169,
    img: "/images/Ferrari_Roma_Spider.jpg",
    maker: "Ferrari",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Mini Cooper",
    cost: 6033834,
    img: "/images/mini_cooper.webp",
    maker: "Mini",
    type: "Hatchback",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Tesla Model 3",
    cost: 8000000,
    img: "/images/tesla-model-3-midnight-silver-1.jpeg",
    maker: "Tesla",
    type: "Sedan",
    fuel_type: "Electric",
    drivetrain: "AWD",
  },
  {
    car: "Bugatti Chiron",
    cost: 212200000,
    img: "/images/bugatti-chiron.jpg",
    maker: "Bugatti",
    type: "Sports",
    fuel_type: "Petrol",
    drivetrain: "RWD",
  },
  {
    car: "Triumph Bonneville T120",
    cost: 1500000,
    img: "/images/Triumph_Bonneville_T120.webp",
    maker: "Triumph",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Triumph Rocket 3",
    cost: 2513948,
    img: "/images/triumph_rocket_3.avif",
    maker: "Triumph",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Triumph Bonneville T100",
    cost: 1258951,
    img: "/images/bonneville-t100.webp",
    maker: "Triumph",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Harley Davidson Fat Bob",
    cost: 3044072,
    img: "/images/fat-boy.webp",
    maker: "Harley Davidson",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Harley Davidson Nightster",
    cost: 1673373,
    img: "/images/nightster.webp",
    maker: "Harley Davidson",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Harley Davidson Sportster S",
    cost: 2059381,
    img: "/images/hd_ss.avif",
    maker: "Harley Davidson",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Ducati Pannigale V4",
    cost: 3403483,
    img: "/images/panigale-v4.webp",
    maker: "Ducati",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Ducati Pannigale V2",
    cost: 2577482,
    img: "/images/panigale-v2.webp",
    maker: "Ducati",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "TVS Iqube",
    cost: 161000,
    img: "/images/tvs_iqube.webp",
    maker: "TVS",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Royal Enfield Classic 350",
    cost: 254000,
    img: "/images/RE_350.webp",
    maker: "Royal Enfield",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Royal Enfield Interceptor 650",
    cost: 395413,
    img: "/images/interceptor_650.webp",
    maker: "Royal Enfield",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Vespa SXL 150",
    cost: 190379,
    img: "/images/vespasxl150.webp",
    maker: "Vespa",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Suzuki Burgman",
    cost: 155902,
    img: "/images/burgman-street.webp",
    maker: "Suzuki",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Yamaha R3",
    cost: 591423,
    img: "/images/r3.webp",
    maker: "Yamaha",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Aprilia RS 457",
    cost: 521697,
    img: "/images/rs_457.webp",
    maker: "Aprilia",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Royal Enfield Shotgun 650",
    cost: 455005,
    img: "/images/re_shotgun650.webp",
    maker: "Royal Enfield",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Royal Enfield Himalayan 450",
    cost: 365009,
    img: "/images/RE_himalayan.webp",
    maker: "Royal Enfield",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Ather 450 apex",
    cost: 203000,
    img: "/images/ather450apex.webp",
    maker: "Ather",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
  {
    car: "Vespa ZX 125",
    cost: 154667,
    img: "/images/vespazx125.webp",
    maker: "Vespa",
    type: "Two Wheeler",
    fuel_type: "Petrol",
    drivetrain: "2WD",
  },
];
